# Generated by Django 5.1.4 on 2024-12-27 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_assigned_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userstudent_class', to='users.gradelevel'),
        ),
    ]
