# Generated by Django 5.1.4 on 2024-12-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todaydate', models.DateTimeField()),
                ('is_present', models.BooleanField(default=False)),
                ('taken_by', models.IntegerField(default=0)),
            ],
        ),
    ]
