# Generated by Django 5.1.4 on 2024-12-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_student_grade_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student_grade_level',
            field=models.IntegerField(),
        ),
    ]
